# Generated by Django 5.1.1 on 2024-10-17 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='user_id',
            new_name='user',
        ),
    ]
