# Generated by Django 5.1.1 on 2024-10-19 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0006_rename_user_id_message_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(blank=True, null=True)),
                ('another_user', models.IntegerField(blank=True, null=True)),
                ('another_user_profile', models.CharField(blank=True, max_length=250, null=True)),
                ('follower', models.IntegerField(blank=True, null=True)),
                ('post', models.IntegerField(blank=True, null=True)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
            ],
        ),
    ]
