# Generated by Django 5.1.1 on 2024-10-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0007_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='another_user_full_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
