# Generated by Django 5.1.1 on 2024-10-19 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0008_notification_another_user_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='another_user_full_name',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='another_user_profile',
        ),
    ]
