# Generated by Django 5.1.1 on 2024-10-19 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0009_remove_notification_another_user_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='another_user',
        ),
    ]
