# Generated by Django 5.1.3 on 2024-12-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0016_premium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premium',
            name='customer_id',
            field=models.CharField(blank=True, null=True),
        ),
    ]
